name: Docker
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:  #ghcr.io/owner/image github actions container register
      image: node:22-alpine3.19
      # credentials: #if your image is private
      #   username:
      #   password:
      env:
        API_URL: some-url.com
      ports:
        - 80
      # volumes:
      #   - vol_name:/path/in/contanier
      #   - /path/to/container
      #   - /path/in/host:/path/in/container
      options: --cpus 1
    steps:
     - name: Log Node & OS Versions
       run: |
         node -v
         cat /etc/os-release
     - name: Log Env
       run: echo $API_URL
     - name: Container in a Step
       uses: docker://node:18.16-alpine3.17
       with:
        entrypoint: /usr/local/bin/node
        args: -p 2+3
     - name: Log version Node
       uses: docker://node:18.16-alpine3.17
       with:
        args: -v