name: External Events
on:
    repository_dispatch:

jobs:
    echo-a-string:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo a string"
              run: echo "Repository Dispatch"