name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo s string
              run: echo "hello World"
            - name: Multiline Command
              run: |
                node -v
                npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers
    dependent-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: echo a string
              run: Write-Output "Windows String"
            - name: Error Step
              run: doesntexits