name: Variables and Secrets
on: [push]

jobs:
    log-vars:
        runs-on: ubuntu-latest
        environment: production
        env:
            BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
            ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
            REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
        steps:
            - name: Run only if BOOLEAN_SECRET is true
              if: env.BOOLEAN_SECRET == 'true'
              run: echo "I run"
            - name: Logs Vars
              run: |
                echo '${{ vars.REPO_LEVEL_VAR }}'
                echo '${{ vars.ENV_LEVEL_VAR }}'