name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Manuel"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: manuelentrena/concurrency-github-actions/.github/workflows/reusable.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  calling-a-reusable-wf2:
    uses: manuelentrena/concurrency-github-actions/.github/workflows/reusable-workflow.yaml@main
  using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-wf2
    steps:
      - run: echo ${{ needs.calling-a-reusable-wf2.outputs.date }}